### ISSUE TITLE
US 01.01.01 As a doer, I want to add a habit, giving it a brief title, reason, and date to start, and whether it is public or private.

### ISSUE THREAD

**Issue by jackie174** [CMPUT301F21T27/TEAM404#2]
Function:
Initialize your habit that you want to add by assigning its basic parameters including title, reason, start date. Indicate if you want your habit to be public so it can be visible for others, and invisible if not.

Quick Notes:
1. Make sure after adding a new habit and assigning parameters, it is then displayed on your personal list of habits, and also added to the database
2. Make sure the date is set up using a date picker, and the default being the device's set up date
3. Make sure if habit is set public, it can be viewed from other accounts, and otherwise if set private

**Comment by Baidadan67** [comment]
risk level: low
