### ISSUE TITLE
Product Backlog

### ISSUE THREAD

**Issue by jackie174** [CMPUT301F21T27/TEAM404#3]

**Comment by lantian-zhao** [comment]
Habits

US 01.01.01
As a doer, I want to add a habit, giving it a brief title, reason, and date to start.

US 01.02.01
As a doer, I want a habit to have a plan for what days of the week it should regularly occur.

US 01.03.01
As a doer, I want to view a given habit and its details.

US 01.04.01
As a doer, I want to edit the details of a habit of mine.

US 01.05.01
As a doer, I want to delete a habit of mine.

US 01.06.01
As a doer, I want a habit title to be up to 20 characters and habit reason to be up to 30 characters.

US 01.07.01
As a doer, I want to see what habits I need to do today.

US 01.08.01
As a doer, I want to see a list of all my habits.

US 01.09.01
As a doer, I want for each habit on the list, a visual indicator to show how closely I am following its plan over time.

Habit Events

US 02.01.01
As a doer, I want to denote a habit event when I have done a habit as planned.

US 02.02.01
As a doer, I want a habit event to have an optional comment of up to 20 characters.

US 02.03.01
As a doer, I want a habit event to have an optional photograph to record what happened.

US 02.04.01
As a doer, I want to view a given habit event and all its available details.

US 02.05.01
As a doer, I want to edit the details of a habit event of mine.

US 02.06.01
As a doer, I want to delete a habit event of mine.

Profile

US 03.01.01
As a doer, I want to be uniquely identifiable in the system.

Habit Following and Sharing

US 05.01.01
As a doer, I want to ask another doer to follow all their habits.

US 05.02.01
As a doer, I want to grant or deny another doer permission to follow all my habits.

US 05.03.01
As a doer, I want to view the habits and visual indicators of the other doers I am granted to follow.

Geolocation and Maps

US 06.01.01
As a doer, I want to a habit event to have an optional location to record where it happened.
